INSERT INTO TBL_COURSE (NAME) VALUES ('Java Script');
INSERT INTO TBL_COURSE (NAME) VALUES ('Java');
INSERT INTO TBL_COURSE (NAME) VALUES ('Python');
INSERT INTO TBL_COURSE (NAME) VALUES ('Ruby');

INSERT INTO TBL_STUDENT (NAME,EMAIL,COURSE_ID,PERIOD,PHONE) VALUES ('Marcos','marcos@abutua.com','1','Manhã','(11) 9898-3232');
INSERT INTO TBL_STUDENT (NAME,EMAIL,COURSE_ID,PERIOD,PHONE) VALUES ('Mateus','mateus@abutua.com','2','Tarde','(11) 8898-3232');
INSERT INTO TBL_STUDENT (NAME,EMAIL,COURSE_ID,PERIOD,PHONE) VALUES ('Carlos','carlos@abutua.com','3','Noite','(11) 7898-3232');
